const SERVICE_URL = process.env.SERVICE_URL || 'http://localhost';
const USHAHIDI_API_URL = process.env.USHAHIDI_API_URL ||'http://localhost:8080';

const WEBHOOK_RECEIVER_SERVICE_URL = process.env.WEBHOOK_RECEIVER_SERVICE_URL || `${SERVICE_URL}:3000`;
const SURVEY_STORAGE_SERVICE_URL = process.env.SURVEY_STORAGE_SERVICE_URL || `${SERVICE_URL}:5002`;
const SURVEY_RESPONSE_SERVICE_URL = process.env.SURVEY_RESPONSE_SERVICE_URL || `${SERVICE_URL}:3002`;
const SURVEY_CREATOR_SERVICE_URL = process.env.SURVEY_CREATOR_SERVICE_URL || `${SERVICE_URL}:3001`;
const AUTH_SERVICE_URL = process.env.AUTH_SERVICE_URL || `${SERVICE_URL}:3003`;

module.exports = {
    SERVICE_URL,
    USHAHIDI_API_URL,
    WEBHOOK_RECEIVER_SERVICE_URL,
    SURVEY_STORAGE_SERVICE_URL,
    SURVEY_RESPONSE_SERVICE_URL,
    SURVEY_CREATOR_SERVICE_URL,
    AUTH_SERVICE_URL,
    USHAHIDI_API_URL,
};